### PR TITLE
set log.queue in conf itself

### LINKED ISSUE #280: Segmentation fault with Conf::setLogCb
* PHP version: 7.2.21 & 7.4-rc1 (both with xdebug)
 * librdkafka version: v1.0.0
 * php-rdkafka version: master
 * kafka version: -

Script crashes with "segmentation fault" while all works fine when explicitly setting ```$conf->set('log.queue', 'true');```:

```php
<?php

use RdKafka\Conf;
use RdKafka\Consumer;

$loggerCallbacks = 0;

$conf = new Conf();
$conf->set('debug', 'consumer');
$conf->set('log_level', (string)LOG_DEBUG);
//$conf->set('log.queue', 'true');
$conf->setLogCb(function (Consumer $consumer, int $level, string $fac, string $buf) use (&$loggerCallbacks) {
    $loggerCallbacks++;
});

$consumer = new Consumer($conf);
do {
    $consumer->poll(0);
} while ($loggerCallbacks === 0);

var_dump($loggerCallbacks); // expect 1
```

### PR DESCRIPTION
**Pull request by nick-zh**
fixes #280
was only done for low level consumer, so i moved the set to conf directly, which makes more sense anyway

### CODE REVIEW

File: conf.c [hunk 1]
```diff
@@ -742,6 +743,7 @@ PHP_METHOD(RdKafka__Conf, setLogCb)
     conf->cbs.log->fcc = fcc;
 
     rd_kafka_conf_set_log_cb(conf->u.conf, kafka_conf_log_cb);
+    rd_kafka_conf_set(conf->u.conf, "log.queue", "true", errstr, sizeof(errstr));
```
Comment (dirx) [inline conf.c:746]: in case log.queue will be set to "false" after setLogCb - remove callback again?

Comment (nick-zh) [reply conf.c:746]: i am not so sure, this feels a bit like magic, i mean if somebody does this, you are like sabotaging yourself :smile:
i totally get your point, but i am not sure if it is worth to cover this, @arnaud-lb thoughts?

**Comment by arnaud-lb** [comment]
Thanks
